version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=0127923a
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
#    build: ../backend
    image: salbad/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: salbad/foodgram_frontend:latest
#    volumes:
#      - ../frontend/:/app/result_build/
    volumes:
      - ../frontend/:/app/result_build/
#    depends_on:
#      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
volumes:
  static_value:
  media_value:
  postgres_value:

